// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParcelApi.Data;

#nullable disable

namespace ParcelApi.Migrations
{
    [DbContext(typeof(ParcelDbContext))]
    [Migration("20260905230744_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ParcelApi.Models.Parcel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("AssessedValue")
                        .HasColumnType("numeric");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("integer");

                    b.Property<double>("BuildingAreaSqFt")
                        .HasColumnType("double precision");

                    b.Property<double>("LandAreaSqFt")
                        .HasColumnType("double precision");

                    b.Property<DateOnly?>("LastSaleDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("LastSalePrice")
                        .HasColumnType("numeric");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Neighbourhood")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Parcels");
                });
#pragma warning restore 612, 618
        }
    }
}
